In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pycaret.classification import *

In [2]:
df = pd.read_csv('../Data/new_data.csv')
df.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,BMI
0,50,2,168,62,110,80,1,1,0,0,1,0,21
1,55,1,156,85,140,90,3,1,0,0,1,1,34
2,51,1,165,64,130,70,3,1,0,0,0,1,23
3,48,2,169,82,150,100,1,1,0,0,1,1,28
4,47,1,156,56,100,60,1,1,0,0,0,0,23

In [3]:
clf_exp = setup(data = df, target = 'cardio')

In [4]:
best_model = compare_models(sort = 'precision')

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

In [5]:
### Just did this for fun if you feel like reading more on this, you should check out Pycaret